import React from "react"
import Image from "next/image"
import { nanoid } from "nanoid"

import { api } from "~/trpc/server"
import { combineToFullName } from "~/lib/combineToFullName"

import BarangayOfficials from "./BarangayOfficials"

export default async function GeneratePage({
  params,
}: {
  params: { profileId: string }
}) {
  const profile = await api.residentProfile.getCompleteName({
    id: params.profileId,
  })

  const currentDate = new Date()
  const day = currentDate.getDate()
  const month = currentDate.toLocaleString("default", { month: "long" })
  const year = currentDate.getFullYear()

  const getDaySuffix = (day: number) => {
    if (day >= 11 && day <= 13) {
      return "th"
    }
    switch (day % 10) {
      case 1:
        return "st"
      case 2:
        return "nd"
      case 3:
        return "rd"
      default:
        return "th"
    }
  }

  return (
    <div className="flex bg-gray-100 print:block">
      <article className="m-10 aspect-[8.3/11] w-1/2 overflow-hidden border-8 bg-white print:m-0 print:h-screen print:w-full print:bg-white">
        <section className="mt-12 flex w-full items-center justify-center gap-12">
          <Image
            src="/logos/sibalom.png"
            width={72}
            height={72}
            alt="Logo of the Municipality of Sibalom"
          />
          <div className="leading-snug">
            <div className="text-center">Republic of the Philippines</div>
            <div className="text-center">Province of Antique</div>
            <div className="text-center">
              Municipality of San Jose de Buenavista
            </div>
            <div className="text-center">Barangay Funda-Dalipe</div>
          </div>
          <Image
            src="/logos/sibalom.png"
            width={72}
            height={72}
            alt="Logo of the Municipality of Sibalom"
          />
        </section>
        <section className="mt-8">
          <div className="text-center text-xl font-medium">
            OFFICE OF THE PUNONG BARANGAY
          </div>
        </section>
        <section className="mt-12 flex w-full gap-8 px-10">
          <BarangayOfficials />
          <article className="w-full">
            <div className="text-center text-2xl font-bold">
              CERTIFICATE OF INDIGENCY
            </div>
            <div className="mt-12">
              <p className="typography-p text-justify">
                TO WHOM IT MAY CONCERN:
              </p>
              <p className="typography-p text-justify">
                This is to certify that{" "}
                <span className="text-justify font-semibold">
                  {combineToFullName([
                    profile?.firstName,
                    profile?.middleName,
                    profile?.lastName,
                    profile?.extensionName,
                  ])}
                </span>
                , of legal age, Filipino, and an identified indigent resident of
                Barangay Catungan IV, Sibalom, Antique.
              </p>
              <p className="typography-p text-justify">
                This certification is issued upon the request of the above-named
                for whatever legal purposes it may serve.
              </p>
              <p className="typography-p text-justify">
                Issued this{" "}
                <span className="font-semibold">
                  {day}
                  {getDaySuffix(day)}
                </span>{" "}
                day of <span className="font-semibold">{month}</span>,{" "}
                <span className="font-semibold">{year}</span> at Barangay Hall
                of Catungan IV, Sibalom, Antique.
              </p>
              <div className="ml-auto mr-10 mt-16 w-fit">
                <p className="text-center">ARMAN L. LEONG-ON</p>
                <p className="text-center">Punong Barangay</p>
              </div>

              <div className="mt-32 w-64">
                <p className="typography-p !mt-0 text-xs text-neutral-600">
                  Reference Number:{" "}
                  <span className="font-semibold">{nanoid(6)}</span>
                </p>
                <p className="typography-p !mt-0 text-xs text-neutral-600">
                  Transaction Number:{" "}
                  <span className="font-semibold">{nanoid(6)}</span>
                </p>
                <p className="typography-p text-xs text-neutral-600">
                  Generated by the Unified Barangay System for Barangay Catungan
                  IV, Sibalom, Antique.
                </p>
              </div>
            </div>
          </article>
        </section>
      </article>
    </div>
  )
}
